### PR TITLE
feat: add support for orpheus

### PR DESCRIPTION
**Pull request by s0up4200**

### CODE REVIEW

**Comment by locke69321** [comment]
When I run this JSON 

`{
  "indexer": {{.Indexer}},
  "user_id": USER_ID,
  "ops_apikey": "OPS_API_KEY",
  "minratio": 1.1,
  "torrent_id": {{.TorrentID}},
  "minsize": 157286400,
  "maxsize": 838860800
}`

I get the error: `Failed to unmarshal JSON payload: invalid character 'o' looking for beginning of value`

If I put quotes or hardcode "ops" I it returns a 500 error.

**Comment by s0up4200** [comment]
> When I run this JSON 
> 
> 
> 
> `{
> 
>   "indexer": {{.Indexer}},
> 
>   "user_id": USER_ID,
> 
>   "ops_apikey": "OPS_API_KEY",
> 
>   "minratio": 1.1,
> 
>   "torrent_id": {{.TorrentID}},
> 
>   "minsize": 157286400,
> 
>   "maxsize": 838860800
> 
> }`
> 
> 
> 
> I get the error: `Failed to unmarshal JSON payload: invalid character 'o' looking for beginning of value`
> 
> 
> 
> If I put quotes around {{.Indexer}} or hardcode "ops" I it returns a 500 error.

Not sure what that is about, but I have pushed some changes. Separate user ids now.

Will test some more later today when I have some time for it.

**Comment by s0up4200** [comment]
Seeing the same issue as you now. Its related to the indexer macro I believe. Will look into it.

**Comment by s0up4200** [comment]
@locke69321 

Add indexer like this: `"indexer": "{{ .Indexer | js }}",`

Tested with RED and was ok there.

**Pull request merged**
